"""Validate config.yml structure and values."""
import click

from scripts import config_utils


@click.command(help='Validate config structure')
@click.option(
    '--full',
    is_flag=True,
    help='Check full config (generated by setup command).',
)
def validate(full: bool):
    """Validate basic or full configuration depending on flag."""
    if full:
        config_utils.print_status('INFO', 'Validating full configuration')
        config_utils.load_config()
    else:
        config_utils.print_status('INFO', 'Validating basic configuration')
        config_utils.load_config(basic=True)

    config_utils.print_status('SUCCESS', 'Configuration is valid!')